import StyledComponentsRegistry from "@/lib/registery";
import "@fontsource/lato";
import { GlobalStyles } from "./styles";
import Footer from "@/component/ui/Footer/Footer";
import Navbar from "@/component/ui/Navbar/Navbar";
// import { assets } from "@/public/assets";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dibo Ruwa",
  description: "Generated by create next app",
  // icons: assets.logo
};

export default function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode;
  authModal: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <StyledComponentsRegistry>
          <Navbar />
          {authModal}
          {children}
          <Footer />
          <GlobalStyles />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
