import StyledComponentsRegistry from "@/lib/registery";
import "@fontsource/lato";
import { GlobalStyles } from "./styles";
import Footer from "@/component/ui/Footer/Footer";
import Navbar from "@/component/ui/Navbar/Navbar";
// import { assets } from "@/public/assets";
import { Metadata } from "next";
import Providers from "@/utils/Providers";
import { assets } from "@/public/assets";

export const metadata: Metadata = {
  title: "Dibo Ruwa",
  description: "Generated by create next app",
  openGraph: {
    type: "website",
    locale: "en_NG",
    url: "https://",
    // site_name: "D",
    images: [
      {
        url: "../",
        width: 1024,
        height: 485,
      },
      {
        url: "../",
        width: 1024,
        height: 485,
      },
    ],
  },
};

export default function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode;
  authModal: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Providers>
          <Navbar />
          {authModal}
          
             {children}
          
         
          <Footer />
          <GlobalStyles />
        </Providers>
      </body>
    </html>
  );
}
